- hosts: 127.0.0.1
  connection: local
  vars:
    - user: mic4ael
    - home: /home/mic4ael
  tasks:
    - name: Installing antigen
      git: repo=https://github.com/zsh-users/antigen.git dest={{ home }}/.antigen

    - name: Linking zsh configuration
      file: src={{ playbook_dir }}/zsh/zshrc dest={{ home }}/.zshrc state=link owner={{ user }}

    - name: Linking vim configuration
      file: src={{ playbook_dir }}/vim/vimrc dest={{ home }}/.vimrc state=link owner={{ user }}

    - name: Linking tmux configuration
      file: src={{ playbook_dir }}/tmux/tmux.conf dest={{ home }}/.tmux.conf state=link owner={{ user }}

    - name: Linking git config
      file: src={{ playbook_dir }}/git/{{ item }} dest={{ home }}/.{{ item }} state=link owner={{ user }}
      with_items:
        - gitignore
        - gitconfig

    - name: Linking ctags config
      file: src={{ playbook_dir }}/ctags/ctags dest={{ home }}/.ctags state=link owner={{ user }}

    - name: Create local bin folder
      file: path={{ home }}/bin state=directory

    - name: Copy scripts to bin directory
      shell: cp {{ playbook_dir }}/scripts/* {{ home }}/bin

    - name: Create go directory
      file: path={{ home }}/go state=directory

    - name: Installing python-devel package
      dnf: name=python-devel; state=present
      become: true
      become_user: root

    - name: Install pipsi
      pip: name={{ item }}
      extra_args: --user
      with_items:
        - pipsi

    - name: Install python-utilities
      shell: pipsi install {{ item }}
      with_items:
        - pew
        - pipenv
        - ipython
        - flake8

- import_playbook: ./osx_play.yml
  when: ansible_distribution == 'MacOSX'

- import_playbook: ./fedora_play.yml
  when: ansible_distribution == 'Fedora'
