#!/bin/bash

brew install ack;
brew install ansible;
brew install asciinema;
brew install asciinema2gif;
brew install aspell;
brew install atk;
brew install autoconf;
brew install cairo;
brew install cmake;
brew install cscope;
brew install ctags;
brew install docker;
brew install docker-machine;
brew install enchant;
brew install fontconfig;
brew install freetype;
brew install gdbm;
brew install gdk-pixbuf;
brew install gettext;
brew install gifsicle;
brew install git;
brew install glib;
brew install glib-networking;
brew install gmp;
brew install gnome-icon-theme;
brew install gnutls;
brew install gobject-introspection;
brew install gsettings-desktop-schemas;
brew install gtk+;
brew install gtk+3;
brew install harfbuzz;
brew install help2man;
brew install hicolor-icon-theme;
brew install htop;
brew install httpie;
brew install hub;
brew install icu4c;
brew install imagemagick;
brew install jpeg;
brew install kotlin;
brew install libepoxy;
brew install libevent;
brew install libffi;
brew install libgcrypt;
brew install libgpg-error;
brew install libidn;
brew install libotr;
brew install libpng;
brew install libsoup;
brew install libssh2;
brew install libtasn1;
brew install libtiff;
brew install libtool;
brew install libyaml;
brew install lzo;
brew install macvim;
brew install mercurial;
brew install midnight-commander;
brew install netcat;
brew install nettle;
brew install node;
brew install openssl;
brew install openvpn;
brew install pango;
brew install pcre;
brew install perl;
brew install phantomjs;
brew install pixman;
brew install pkg-config;
brew install portmidi;
brew install pv;
brew install pyenv;
brew install pyenv-virtualenvwrapper;
brew install python;
brew install python3;
brew install qt;
brew install qt5;
brew install readline;
brew install reattach-to-user-namespace;
brew install ruby;
brew install rust;
brew install s-lang;
brew install scala;
brew install sdl;
brew install sdl2;
brew install sdl_image;
brew install sdl_mixer;
brew install sdl_ttf;
brew install sqlite;
brew install the_silver_searcher;
brew install tig;
brew install tmux;
brew install tree;
brew install vala;
brew install vifm;
brew install vim;
brew install webkitgtk;
brew install webp;
brew install weechat;
brew install wget;
brew install xz;
brew install znc;
brew install zsh;


# Brew Cask
brew cask install atom;
brew cask install calibre;
brew cask install cinch;
brew cask install evernote;
brew cask install flux;
brew cask install google-chrome;
brew cask install iterm2;
brew cask install java;
brew cask install libreoffice;
brew cask install middleclick;
brew cask install messenger;
brew cask install slack;
brew cask install spotify;
brew cask install steam;
brew cask install telegram;
brew cask install virtualbox;
brew cask install vlc;
brew cask install wireshark;
brew cask install the-unarchiver;
brew cask install transmission;

brew linkapps;

brew cleanup;brew cask cleanup;
