#!/bin/bash;

brew install asdf;
brew install ansible;
brew install asciinema;
brew install asciinema2gif;
brew install boost;
brew install cloog;
brew install ctags;
brew install curl;
brew install dirmngr;
brew install flex;
brew install fortune;
brew install git;
brew install gnome-icon-theme;
brew install gnupg;
brew install gpg-agent;
brew install gradle;
brew install gtk+;
brew install htop;
brew install httpie;
brew install libcaca;
brew install libgphoto2;
brew install libicns;
brew install libidn;
brew install libmpc@0.8;
brew install libotr;
brew install libxml2;
brew install libzip;
brew install little-cms2;
brew install macvim;
brew install maven;
brew install mcrypt;
brew install mercurial;
brew install midnight-commander;
brew install netcat;
brew install nmap;
brew install node;
brew install openvpn;
brew install perl;
brew install portmidi;
brew install pv;
brew install pyenv-virtualenvwrapper;
brew install python3;
brew install qt;
brew install reattach-to-user-namespace;
brew install sane-backends;
brew install sdl2;
brew install sdl_image;
brew install sdl_mixer;
brew install sdl_ttf;
brew install ssh-copy-id;
brew install the_silver_searcher;
brew install tig;
brew install tmux;
brew install tree;
brew install unixodbc;
brew install unrar;
brew install utf8proc;
brew install webkitgtk;
brew install weechat;
brew install wget;
brew install wxmac;
brew install zsh;


# Brew Cask
brew cask install cinch;
brew cask install evernote;
brew cask install firefox;
brew cask install garmin-express;
brew cask install google-chrome;
brew cask install google-drive;
brew cask install iterm2;
brew cask install java;
brew cask install libreoffice;
brew cask install mactex;
brew cask install middleclick;
brew cask install qt-creator;
brew cask install spotify;
brew cask install steam;
brew cask install the-unarchiver;
brew cask install toggldesktop;
brew cask install transmission;
brew cask install tunnelblick;
brew cask install virtualbox;
brew cask install visual-studio-code;
brew cask install vlc;
brew cask install wireshark;

brew linkapps;
brew cleanup;
brew cask cleanup;
