#!/bin/bash

brew install adns;
brew install ansible;
brew install asciinema;
brew install asciinema2gif;
brew install aspell;
brew install atk;
brew install autoconf;
brew install automake;
brew install boost;
brew install cairo;
brew install cloog;
brew install cmake;
brew install cscope;
brew install ctags;
brew install curl;
brew install dirmngr;
brew install enchant;
brew install flex;
brew install fontconfig;
brew install fortune;
brew install freetype;
brew install gd;
brew install gdbm;
brew install gdk-pixbuf;
brew install gettext;
brew install gifsicle;
brew install git;
brew install glib;
brew install glib-networking;
brew install gmp;
brew install gmp@4;
brew install gnome-icon-theme;
brew install gnupg;
brew install gnupg2;
brew install gnutls;
brew install gobject-introspection;
brew install gpg-agent;
brew install gradle;
brew install gsettings-desktop-schemas;
brew install gtk+;
brew install gtk+3;
brew install harfbuzz;
brew install help2man;
brew install hicolor-icon-theme;
brew install htop;
brew install httpie;
brew install icu4c;
brew install imagemagick;
brew install isl@0.12;
brew install jasper;
brew install jpeg;
brew install libassuan;
brew install libcaca;
brew install libepoxy;
brew install libevent;
brew install libffi;
brew install libgcrypt;
brew install libgpg-error;
brew install libgphoto2;
brew install libicns;
brew install libidn;
brew install libksba;
brew install libmpc@0.8;
brew install libotr;
brew install libpng;
brew install libsoup;
brew install libssh2;
brew install libtasn1;
brew install libtiff;
brew install libtool;
brew install libunistring;
brew install libusb;
brew install libusb-compat;
brew install libxml2;
brew install libyaml;
brew install libzip;
brew install little-cms2;
brew install lzo;
brew install macvim;
brew install makedepend;
brew install maven;
brew install mcrypt;
brew install mercurial;
brew install mhash;
brew install midnight-commander;
brew install mpfr@2;
brew install net-snmp;
brew install netcat;
brew install nettle;
brew install nmap;
brew install node;
brew install npth;
brew install openssl;
brew install openssl@1.1;
brew install openvpn;
brew install p11-kit;
brew install pango;
brew install pcre;
brew install perl;
brew install phantomjs;
brew install pinentry;
brew install pixman;
brew install pkg-config;
brew install portmidi;
brew install pth;
brew install pv;
brew install pyenv;
brew install pyenv-virtualenvwrapper;
brew install python;
brew install python3;
brew install qt;
brew install qt5;
brew install readline;
brew install reattach-to-user-namespace;
brew install s-lang;
brew install sane-backends;
brew install sdl;
brew install sdl2;
brew install sdl_image;
brew install sdl_mixer;
brew install sdl_ttf;
brew install shared-mime-info;
brew install sqlite;
brew install ssh-copy-id;
brew install the_silver_searcher;
brew install tig;
brew install tmux;
brew install tree;
brew install unixodbc;
brew install unrar;
brew install utf8proc;
brew install vala;
brew install webkitgtk;
brew install webp;
brew install weechat;
brew install wget;
brew install wxmac;
brew install xz;
brew install zsh;


# Brew Cask
brew cask install cinch;
brew cask install evernote;
brew cask install garmin-express;
brew cask install google-chrome;
brew cask install google-drive;
brew cask install iterm2;
brew cask install java;
brew cask install libreoffice;
brew cask install mactex;
brew cask install middleclick;
brew cask install qt-creator;
brew cask install spotify;
brew cask install steam;
brew cask install the-unarchiver;
brew cask install transmission;
brew cask install tunnelblick;
brew cask install virtualbox;
brew cask install visual-studio-code;
brew cask install vlc;
brew cask install wireshark;

brew linkapps;

brew cleanup;brew cask cleanup;
