source ~/.antigen/antigen.zsh

# The following lines were added by compinstall
zstyle :compinstall filename '/home/mic4ael/.zshrc'

autoload -Uz compinit && compinit
# End of lines added by compinstall

# Load the oh-my-zsh's library.
antigen use oh-my-zsh

# Bundles from the default repo (robbyrussell's oh-my-zsh).
antigen bundle git
antigen bundle heroku
antigen bundle pip
antigen bundle lein
antigen bundle command-not-found

# Syntax highlighting bundle.
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle zsh-users/zsh-completions
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle peterhurford/git-aliases.zsh

# Load the theme.
antigen theme gnzh

# Tell antigen that you're done.
antigen apply

for f in $(find ~/.dotfiles/zsh -maxdepth 1 -name "*.zsh");
do
  source $f;
done;

export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=11'

man() {
  env \
    LESS_TERMCAP_mb=$(printf "\e[1;31m") \
    LESS_TERMCAP_md=$(printf "\e[1;31m") \
    LESS_TERMCAP_me=$(printf "\e[0m") \
    LESS_TERMCAP_se=$(printf "\e[0m") \
    LESS_TERMCAP_so=$(printf "\e[1;44;33m") \
    LESS_TERMCAP_ue=$(printf "\e[0m") \
    LESS_TERMCAP_us=$(printf "\e[1;32m") \
  man "$@"
}

export HISTCONTROL=ignoreboth:erasedups;
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

export GOPATH=$HOME/go
export PATH="$GOPATH/bin:${HOME}/.local/bin:${HOME}/bin:/usr/local/sbin:/usr/local/bin:/usr/local/opt/gettext/bin:$PATH"
export PATH="$HOME/.cargo/bin:/usr/local/opt/postgresql@9.6/bin:$PATH"

# The following lines were added by compinstall
zstyle :compinstall filename "$HOME/.zshrc"

autoload -Uz compinit
compinit
# End of lines added by compinstall

source $(pew shell_config)
