source ~/.antigen/antigen.zsh

export HISTCONTROL=ignoreboth:erasedups;
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

export PATH="$([ -z $VIRTUAL_ENV ] && echo '' || echo "$VIRTUAL_ENV/bin"):/usr/local/sbin:/usr/local/bin:${PATH}:$GOPATH/bin:${HOME}/.local/bin:${HOME}/bin:usr/local/opt/gettext/bin"
export PATH="${PATH}:$HOME/.cargo/bin:/usr/local/opt/postgresql@9.6/bin:$HOME/Library/Python/2.7/bin"
export GOPATH=$HOME/go
export GOROOT=$(go env GOROOT)
export ANDROID_SDK_ROOT='/usr/local/share/android-sdk'

# Load the oh-my-zsh's library.
antigen use oh-my-zsh

# Bundles from the default repo (robbyrussell's oh-my-zsh).
antigen bundle git
antigen bundle heroku
antigen bundle pip
antigen bundle lein
antigen bundle command-not-found

# Syntax highlighting bundle.
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle zsh-users/zsh-completions
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle peterhurford/git-aliases.zsh

# Load the theme.
antigen theme gnzh

# Tell antigen that you're done.
antigen apply

source ~/.dotfiles/zsh/*.zsh

export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=11'

man() {
  env \
    LESS_TERMCAP_mb=$(printf "\e[1;31m") \
    LESS_TERMCAP_md=$(printf "\e[1;31m") \
    LESS_TERMCAP_me=$(printf "\e[0m") \
    LESS_TERMCAP_se=$(printf "\e[0m") \
    LESS_TERMCAP_so=$(printf "\e[1;44;33m") \
    LESS_TERMCAP_ue=$(printf "\e[0m") \
    LESS_TERMCAP_us=$(printf "\e[1;32m") \
  man "$@"
}

# The following lines were added by compinstall
zstyle :compinstall filename "$HOME/.zshrc"
autoload -Uz compinit
compinit
# End of lines added by compinstall

eval "$(jenv init -)"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
